### ISSUE TITLE
Todo : v2

### ISSUE THREAD

**Issue by vividvilla** [vividvilla/olaf#3]
### To do's
- [ ] Google CSE integration
- [ ] Migration tool for WordPress
- [ ] Test coverage
- [ ] Visual post creator
	- [ ] New posts
	- [ ] Edit posts
	- [ ] Delete posts
	- [ ] markdown preview
- [x] Cli post creator
	- [x] New posts
	- [ ] Edit posts
	- [ ] Delete posts
